config/routes.rb
Rails.application.routes.draw do
  get 'card/new'
  get 'card/show'
  devise_for :users
  root to: 'goods#index'
  resources :users, only:[:show, :destroy]

 

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  
  resources :goods, only:[:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :good_images, only: [:index, :new, :create]
  end

  
  resources :orders, only: [:index] do
    collection do
      get 'index', to: 'orders#index'
      post 'pay', to: 'orders#pay'
      get 'done', to: 'orders#done'
    end
  end

  resources :users, only:[:goods_sale] do
    member do
      get 'goods_sale'
    end
  end

  resources :users, only:[:goods_buy] do
    member do
      get 'goods_buy'
    end
  end

  resources :users, only:[:goods_list] do
    member do
      get 'goods_list'
    end
  end

  namespace :api do
    resources controller: :goods, only: :child, defaults: { format: 'json' } do
      collection do
        get 'child'
      end
    end
    resources controller: :goods, only: :grand_child, defaults: { format: 'json' } do
      collection do
        get 'grand_child'
      end
    end
  end
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # 以下のコメントアウトは実装するタイミングで随時コメントアウトを外す
  
  # has_many :comments, through: :users_comments, dependent: :destroy
  # has_many :users_comments, dependent: :destroy
  # has_many :cards, dependent: :destroy
  # has_many :orders

  has_many :buyed_goods, foreign_key: "buyer_id", class_name: "Good", dependent: :destroy
  has_many :selling_goods, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Good", dependent: :destroy
  has_many :sold_goods, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Good", dependent: :destroy
  has_many :orders
  has_many :user_addresses

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,30}\z/i
  VALID_KANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_POSTCODE_REGEX = /\A\d{7}\z/

  validates_confirmation_of :password  
  attr_accessor :password_confirmation

  validates :nickname,              uniqueness: true, length: { maximum: 10 }
  validates :email,                 allow_blank: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password,              allow_blank: true, format: { with: VALID_PASSWORD_REGEX, message: 'は英字と数字両方を含んで設定してください' }, length: { in: 7..30 }
  validates :password_confirmation, presence: true
  validates :last_name,             length: { maximum: 20 }
  validates :first_name,            length: { maximum: 20 }
  validates :last_name_kana,        allow_blank: true, format: { with: VALID_KANA_REGEX, message: 'はカタカナで入力して下さい' }, length: { maximum: 20 }
  validates :first_name_kana,       allow_blank: true, format: { with: VALID_KANA_REGEX, message: 'はカタカナで入力して下さい' }, length: { maximum: 20 }
  validates :postcode,              allow_blank: true, format: { with: VALID_POSTCODE_REGEX}, length: { maximum: 7 }
  validates :prefecture,            length: { maximum: 20 }
  validates :city,                  length: { maximum: 20 }
  validates :block,                 length: { maximum: 20 }

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :birth_year
    validates :birth_month
    validates :birth_day
    validates :postcode
    validates :prefecture
    validates :city
    validates :block
  end

  mount_uploader :image, ImageUploader

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_hash
  
  def show
    @goods = Good.where(seller_id: current_user.id)
  end

  def destroy
  end

  def goods_sale
    @goods = Good.where(seller_id: current_user.id).order(id: "DESC").page(params[:page])
  end

  def goods_list
    @goods = Good.where(seller_id: current_user.id).order(id: "DESC").page(params[:page]).per(5)
  end

  def goods_buy
    @goods = Good.where(buyer_id: current_user.id).order(id: "DESC").page(params[:page])
  end

  private
  def set_hash
    @contents = ["マイページ","お知らせ","やることリスト","いいね！一覧","出品する","下書き一覧","出品した商品-出品中","出品した商品-取引中","出品した商品-売却済み","購入した商品-取引中","購入した商品-過去の取引","ニュース一覧","評価一覧","ガイド","お問い合わせ"]
    @options = ["プロフィール","発送元・お届先住所変更","支払い方法","メール/パスワード","本人情報","電話番号の確認","ログアウト"]
    @todos = ["【重要】2020/04/04(土) AM03:00 ~ AM03:45 システムメンテナンスのお知らせ","《春得出品祭》当選者へのご連絡・山分けポイント付与対象者へのポイント付与を完了しました"]
    @goods = ["スニーカー","プレイステーション4","iPhone11","MacBookPro"]
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage-side.html.haml
.mypage__side
  %ul.mypage__side__list
    -@contents.each do |content|
      -if content == "マイページ"
        %li.mypage__side--item
          =link_to user_path(current_user), class:"btn item" do
            =content
      -elsif content == "出品する"
        %li.mypage__side--item
          =link_to new_good_path,data: {"turbolinks" => false}, class:"btn item" do
            =content
      -elsif content == "出品した商品-出品中"
        %li.mypage__side--item
          =link_to goods_list_user_path(current_user), class:"btn item" do
            =content
      -elsif content == "出品した商品-売却済み"
        %li.mypage__side--item
          =link_to goods_sale_user_path(current_user), class:"btn item" do
            =content
      -elsif content == "購入した商品-過去の取引"
        %li.mypage__side--item
          =link_to goods_buy_user_path(current_user), class:"btn item" do
            =content
            
      -else
        %li.mypage__side--item
          =link_to "#", class:"btn item" do
            =content

  .mypage__side__option
    設定
  %ul.mypage__side__list
    -@options.each do |option|
      -if option == "ログアウト"
        %li.mypage__side--item
          =link_to user_path(current_user), method: :delete, class:"item" do
            =option
      -elsif option == "支払い方法"
        %li.mypage__side--item
          =link_to new_card_path, class:"item" do
            =option
      -else
        %li.mypage__side--item
          =link_to "#", class:"item" do
            =option

app/views/users/destroy.html.haml
= render "goods/header"

.main
  .logout-content
    = render "mypage-side"
    .logout-content__main
      .logout-content__main__btn
        =link_to "/users/sign_out",method: :delete, class:'btn' do
          %button.btn
            ログアウト

= render "goods/indfooter"

app/views/users/goods_buy.html.haml
= render "goods/header"
.main
  .mypage
    = render "mypage-side"

    .goods
      .goods__top
        購入した商品
      %ul.goods__list
        -@goods.each do |good|
          = link_to good_path(good.id), method: :get, class:"good_link" do
            %li.goods__list__box
              .goods__list__box--image
                = image_tag good.good_images[0].image.url, size: "60x60"
              .goods__list__box--text
                .goods__list__box--text__name
                  = good.name
                .goods__list__box--text__sale
                  購入
        .paginate            
          = paginate(@goods)

=render "goods/indfooter"

app/views/users/goods_buy_fin.html.haml
= render "goods/header"
.main
  .mypage
    = render "mypage-side"

    .goods
      .goods__top
        取引中の商品
      %ul.goods__list
        -@goods.each do |good|
          -if good.trading_conditions == 3
            = link_to good_path(good.id), method: :get, class:"good_link" do
              %li.goods__list__box
                .goods__list__box--image
                  = image_tag good.good_images[0].image.url, size: "60x60"
                .goods__list__box--text
                  .goods__list__box--text__name
                    = good.name
                  .goods__list__box--text__sale
                    購入
          .paginate            
            = paginate(@goods)

=render "goods/indfooter"

app/views/users/goods_list.html.haml
= render "goods/header"
.main
  .mypage
    = render "mypage-side"

    .goods
      .goods__top
        出品した商品
      %ul.goods__list
        -@goods.each do |good|
          = link_to good_path(good.id), method: :get, class:"good_link" do
            %li.goods__list__box
              .goods__list__box--image
                = image_tag good.good_images[0].image.url, size: "60x60"
              .goods__list__box--text
                .goods__list__box--text__name
                  = good.name
                -if good.buyer_id == nil
                  .goods__list__box--text__sale
                    販売中
                -else
                  .goods__list__box--text__sold-out
                    SOLD OUT
        .paginate            
          = paginate(@goods)

=render "goods/indfooter"

app/views/users/goods_sale.html.haml
= render "goods/header"
.main
  .mypage
    = render "mypage-side"

    .goods
      .goods__top
        売却した商品
      %ul.goods__list
        -@goods.each do |good|
          = link_to good_path(good.id), method: :get, class:"good_link" do
            %li.goods__list__box
              -if good.buyer_id != nil
                .goods__list__box--image
                  = image_tag good.good_images[0].image.url, size: "60x60"
                .goods__list__box--text
                  .goods__list__box--text__name
                    = good.name
                    .goods__list__box--text__sold-out
                      SOLD OUT
        .paginate            
          = paginate(@goods)

=render "goods/indfooter"

app/views/users/show.html.haml
= render "goods/header"
.main
  .mypage
    = render "mypage-side"

    .mypage__main
      .mypage__main__user
        .mypage__main__user__top
          .mypage__main__user__top__background
            =image_tag "background2.png", size:'750x250'
          .mypage__main__user__top__box
            .mypage__main__user__top__box__icon
              = link_to edit_user_registration_path do
                - if "#{current_user.image}" == "" or "#{current_user.image}" == nil
                  =image_tag "no_icon.png", class:"icon", size:'120x120'
                - else
                  = image_tag("#{current_user.image}", class:"icon", size:'120x120')
            .mypage__main__user__top__box__name
              = current_user.nickname
            .mypage__main__user__top__box__info
              .mypage__main__user__top__box__info__review
                評価：7
              .mypage__main__user__top__box__info__exhibit
                出品数：
                = @goods.length
          
        .mypage__main__user__tags
          .mypage__main__user__tags__tag.active
            お知らせ
          .mypage__main__user__tags__tag
            やることリスト
        %ul.mypage__main__user__lists
          %li.none
            .none__icon
              = image_tag "mark.png", size:'100x100'
            .none__text
              お知らせはありません

          -@todos.each do |todo|
            %li.box
              .box__mark
                = image_tag "mark.png", size:'50x50'
              .box__list
                .box__list__text
                  =todo
                .box__list__date
                  23時間前
          
        .mypage__main__user__index
          .mypage__main__user__index__btn
            =button_tag "一覧を見る", class:"index_btn"
      .mypage__main__goods
        .mypage__main__goods__title
          購入した商品
        .mypage__main__goods__tags
          .mypage__main__goods__tags__tag.active
            取引中
          .mypage__main__goods__tags__tag
            過去の取引
        %ul.mypage__main__goods__list
          -@goods.each do |good|
            %li.box
              .box__mark
                = image_tag "mark.png", size:'50x50'
              .box__list
                .box__list__text
                  =good
                .box__list__date
                  23時間前
          %li.mypage__main__goods__none
            .none__icon
            = image_tag "mark.png", size:'100x100'
            .none__text
              取引中の商品がありません

=render "goods/indfooter"