config/routes.rb
Rails.application.routes.draw do
  get 'card/new'
  get 'card/show'
  devise_for :users
  root to: 'goods#index'
  resources :users, only:[:show, :destroy]

 

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  
  resources :goods, only:[:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :good_images, only: [:index, :new, :create]
  end

  
  resources :orders, only: [:index] do
    collection do
      get 'index', to: 'orders#index'
      post 'pay', to: 'orders#pay'
      get 'done', to: 'orders#done'
    end
  end

  resources :users, only:[:goods_sale] do
    member do
      get 'goods_sale'
    end
  end

  resources :users, only:[:goods_buy] do
    member do
      get 'goods_buy'
    end
  end

  resources :users, only:[:goods_list] do
    member do
      get 'goods_list'
    end
  end

  namespace :api do
    resources controller: :goods, only: :child, defaults: { format: 'json' } do
      collection do
        get 'child'
      end
    end
    resources controller: :goods, only: :grand_child, defaults: { format: 'json' } do
      collection do
        get 'grand_child'
      end
    end
  end
  

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :good  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  require 'payjp'
  before_action :check_user_login
  before_action :set_good
  before_action :set_address
  before_action :set_card
  before_action :check_current_user
  before_action :check_buyer_id, except: :done

  def index
    if @card.blank? 
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    @good.buyer_id = current_user.id
    if @good.save
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      Payjp::Charge.create(
      :amount => @good.price,
      :customer => @card.customer_id,
      :currency => 'jpy',
      )
      flash[:notice] = "購入が完了しました。"
      redirect_to done_orders_path(@good.id)
    else
      flash[:alert] = '購入できませんでした。'
      redirect_to orders_path(@good.id)
    end
  end
  
  def done
    if @good.buyer_id.blank?
      redirect_to root_path
      flash[:alert] = '不正なアクセスです'
    end
  end

  private

  def set_good
    @good = Good.find(params[:format])
    @image = GoodImage.find_by(good_id:@good.id)
  end

  def set_address
    @address = (current_user.prefecture + current_user.city + current_user.block)
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def check_current_user
    if current_user.id == @good.seller_id
      redirect_to root_path
      flash[:alert] = '自分の商品は購入できません'
    end
  end

  def check_buyer_id
    if @good.buyer_id.present?
      redirect_to root_path
      flash[:alert] = '不正なアクセスです'
    end
  end

  def check_user_login
    unless user_signed_in?
      redirect_to root_path
      flash[:alert] = 'ログインしてください'
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/done.html.haml
.goRootPage
  %h1.goRootPage__icon
    = link_to "/" do
      = image_tag "logo.png",size: '134x36',alt:"FURIMA"

.main
  .done
    .done__info
      .done__info__box
        .done__info__box--icon
          = icon("far", "clock")
        .done__info__box--text
          発送までしばらくおまちください
      .done__info--message
        出品者からの発送通知をお待ちください
    .done__top
      購入が完了しました！
    .done__box
      .done__box__image
        =image_tag("#{@image.image}",size: '150x150')
      .done__box__name
        = @good.name
    .done__price
      = @good.price 
      円(送料込み)
    .done__btn
      =link_to good_path(@good.id), method: :get do
        = submit_tag "商品詳細ページに戻る" ,class: "btn"
    .done__btn
      = link_to user_path(current_user.id), method: :get do
        = submit_tag "マイページに戻る" ,class: "btn"

.footer
  %ul.contents
    %li.content
      %h2.content__title
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            %span  会社概要
        %li
          = link_to "#" do
            %span  プライバシーポリシー
        %li
          = link_to "#" do
            %span  FURIMA利用規約
        %li
          = link_to "#" do
            %span  ポイントに関する特約
    %li.content
      %h2.content__title
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            %span  カテゴリー一覧
        %li
          = link_to "#" do
            %span  ブランド一覧
    %li.content
      %h2.content__title
        ヘルプ＆ガイド
      %ul  
        %li
          = link_to "#" do
            %span  FURIMAガイド
        %li
          = link_to "#" do
            %span  FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            %span  お知らせ
  .footer__logo
    %span.image
      = image_tag "logo-white.png", size:'134x36'
      %p  ©︎フリマ

app/views/orders/index.html.haml
.goRootPage
  %h1.goRootPage__icon
    = link_to "/" do
      = image_tag "logo.png",size: '134x36',alt:"FURIMA"
      
.mainContent
  .setBuyPage
    .setBuyPage__head
      購入内容の確認
    .setBuyPage__goods
      .setBuyPage__goods__main
        .setBuyPage__goods__main__image
          = image_tag("#{@image.image}",size: '150x150')
        .setBuyPage__goods__main__detail
          .setBuyPage__goods__main__detail__price
            = @good.name
    .setBuyPage__price
      .setBuyPage__price__main
        .setBuyPage__price__main__word
          お支払い金額
        .setBuyPage__price__main__price
          = @good.price
          円
    .setBuyPage__howToPay
      .setBuyPage__howToPay__word
        お支払い方法　　　クレジットカード（一括）
    .setBuyPage__adressZone
      .setBuyPage__adressZone__word
        お届け先
      .setBuyPage__adressZone__adress
        = @address
    .setBuyPage__buyBtn
      .setBuyPage__buyBtn__main
        .setBuyPage__buyBtn__btn
          = form_tag(pay_orders_path(@good.id), method: :post) do
            %button.btn 購入する

.footer
  %ul.contents
    %li.content
      %h2.content__title
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            %span  会社概要
        %li
          = link_to "#" do
            %span  プライバシーポリシー
        %li
          = link_to "#" do
            %span  FURIMA利用規約
        %li
          = link_to "#" do
            %span  ポイントに関する特約
    %li.content
      %h2.content__title
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            %span  カテゴリー一覧
        %li
          = link_to "#" do
            %span  ブランド一覧
    %li.content
      %h2.content__title
        ヘルプ＆ガイド
      %ul  
        %li
          = link_to "#" do
            %span  FURIMAガイド
        %li
          = link_to "#" do
            %span  FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            %span  お知らせ
  .footer__logo
    %span.image
      = image_tag "logo-white.png", size:'134x36'
      %p  ©︎フリマ