config/routes.rb
Rails.application.routes.draw do
  get 'card/new'
  get 'card/show'
  devise_for :users
  root to: 'goods#index'
  resources :users, only:[:show, :destroy]

 

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  
  resources :goods, only:[:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :good_images, only: [:index, :new, :create]
  end

  
  resources :orders, only: [:index] do
    collection do
      get 'index', to: 'orders#index'
      post 'pay', to: 'orders#pay'
      get 'done', to: 'orders#done'
    end
  end

  resources :users, only:[:goods_sale] do
    member do
      get 'goods_sale'
    end
  end

  resources :users, only:[:goods_buy] do
    member do
      get 'goods_buy'
    end
  end

  resources :users, only:[:goods_list] do
    member do
      get 'goods_list'
    end
  end

  namespace :api do
    resources controller: :goods, only: :child, defaults: { format: 'json' } do
      collection do
        get 'child'
      end
    end
    resources controller: :goods, only: :grand_child, defaults: { format: 'json' } do
      collection do
        get 'grand_child'
      end
    end
  end
  

end

app/models/good.rb
class Good < ApplicationRecord
#コメントアウト部は後に使用
 # has_many :buyed_goods, foreign_key: "buyer_id", class_name: "Good", dependent: :destroy
  # has_many :comments, through: :users_comments, dependent: :destroy
 # has_many :users_comments, dependent: :destroy
 # belongs_to :user_address

 
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  has_one :category
  has_many :orders
  has_many :good_images, dependent: :destroy
  accepts_nested_attributes_for :good_images, allow_destroy: true


  VALID_PRICE_REGEX = /\A[0-9]+\z/

  validates :name, presence: true, length: { maximum: 40 }
  validates :price, presence: true, format:{ with: VALID_PRICE_REGEX }, inclusion: 300..9999999
  validates :state,                 presence: true
  validates :region,                presence: true
  validates :postage,               presence: true
  validates :expanation,            presence: true, length: { maximum: 400 }
  validates :shipping_date,         presence: true
  validates :delivery_method_id,    presence: true
  validates :category_id,           presence: true
  validates :seller_id,             presence: true 
  validates :good_images,           presence: true


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size
  belongs_to_active_hash :delivery_method
  belongs_to_active_hash :trading_conditions

end

app/controllers/api/goods_controller.rb
class Api::GoodsController < ApplicationController

  def child
    @child_categories = Category.where('ancestry = ?', "#{params[:id]}")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def grand_child
    unless params[:id].empty?
      id = "/" + "#{params[:id]}"
      @grand_child_categories = Category.where('ancestry LIKE(?)', "%#{id}")
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :move_to_index, only:[:edit, :update, :destroy]
  before_action :find_good, only: [:edit, :update, :destroy]
  

  def index
    @goods_all = Good.all
    @goods = Good.where(buyer_id: nil).limit(3).order(id: "DESC")

    @goods_women_new  = Good.where(buyer_id: nil, category_id: [20..85]).limit(3).order(id: "DESC")
    @goods_mens_new = Good.where(buyer_id: nil, category_id: [86..144]).limit(3).order(id: "DESC")

    @good_images = GoodImage.where(id: @goods_all.ids)
  end

  def new
    if user_signed_in?
      @good = Good.new
      @good.good_images.new
    else
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end
  end

  def show
    @good_detail = Good.find(params[:id])

    @good_user = User.find(@good_detail.seller_id)
    @good_size = Size.find(@good_detail.size_id) 

    @category_grand_children = Category.find(@good_detail.category_id)
    @category_children = @category_grand_children.parent
    @category_parent = @category_children.parent

  end

  def edit
    if current_user.id == @good.seller_id
      @category_grandchild = Category.find(@good.category_id)
      @category_child = @category_grandchild.parent
      @category_parent = @category_child.parent
    else
      flash[:alert] = "不正な操作です"
      redirect_to root_path
    end
  end

  def update
    if @good.update(good_update_params) && current_user.id == @good.seller_id
      flash[:notice] = "商品の編集が完了しました"
    else
      flash[:alert] = "商品の編集に失敗しました"
      redirect_to edit_good_path(@good.id)
    end
  end

  def destroy
    if @good.destroy && current_user.id == @good.seller_id
      flash[:notice] = "商品の削除が完了しました"
    else
      flash[:alert] = "商品の削除に失敗しました"
      redirect_to good_path(@good_detail)
    end
  end

  def create
    @good_image = GoodImage.new
    @good = Good.new(good_params)
    if @good.save 
      flash[:notice] = "出品が完了しました"
      redirect_to root_path
    else
      flash[:alert] = '出品に失敗しました。必須項目を確認してください。'
      redirect_to new_good_path
    end
  end
  

  private

  def good_params
    params.require(:good).permit(:name, :state, :size_id, :region, :postage, :category_id, :expanation, :shipping_date, :delivery_method_id, :trading_conditions_id, :price, good_images_attributes: [:image]).merge( seller_id: current_user.id)
  end

  def good_update_params
    params.require(:good).permit(:name, :state, :size_id, :region, :postage, :category_id, :expanation, :shipping_date, :delivery_method_id, :trading_conditions_id, :price, good_images_attributes: [:image, :_destroy, :id]).merge( seller_id: current_user.id)
  end

  def find_good
    @good = Good.find(params[:id])
  end

  def move_to_index
    @good = Good.find(params[:id])
    redirect_to action: :index unless user_signed_in? && current_user.id == @good.seller_id 
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/goods/_header.html.haml
.top-header
  .main-header
    .main-header__top
      %h1.main-header__top__icon
        = link_to root_path do
          = image_tag "logo.png",size: '134x36',alt:"FURIMA"
      .main-header__top__searchbox
        .main-header__top__searchbox__input-box
          %input{type: "text", class: "main-header__top__searchbox__input-box__text", placeholder: "キーワードから探す"}
          %button{title: "検索", type: "submit", class: "main-header__top__searchbox__input-box__submit-btn"}
            = image_tag "icon-search 1.png",size: '19x19',alt:"FURIMA"
    .main-header__nav
      %ul.main-header__nav__left
        %li.main-header__nav__left__category
          = link_to "#" do
            %span カテゴリ
        %li.main-header__nav__left__brand
          = link_to "#" do
            %span ブランド
      %ul.main-header__nav__right
        -if user_signed_in?
          %li.main-header__nav__right__page
            = link_to "マイページ", user_path(current_user)
          %li.main-header__nav__right__log
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        -else 
          %li.main-header__nav__right__page
            =link_to "新規登録", new_user_registration_path
          %li.main-header__nav__right__log
            = link_to "ログイン", new_user_session_path 
       

app/views/goods/_indfooter.html.haml
.footer
  %ul.contents
    %li.content
      %h2.content__title
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            %span  会社概要
        %li
          = link_to "#" do
            %span  プライバシーポリシー
        %li
          = link_to "#" do
            %span  FURIMA利用規約
        %li
          = link_to "#" do
            %span  ポイントに関する特約
    %li.content
      %h2.content__title
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            %span  カテゴリー一覧
        %li
          = link_to "#" do
            %span  ブランド一覧
    %li.content
      %h2.content__title
        ヘルプ＆ガイド
      %ul  
        %li
          = link_to "#" do
            %span  FURIMAガイド
        %li
          = link_to "#" do
            %span  FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            %span  お知らせ
  .footer__logo
    %span.image
      = image_tag "logo-white.png", size:'134x36'
      %p  ©︎フリマ

app/views/goods/_indmain.html.haml
.main-contents 
  .top-picture
    .top-picture__body
      %h.top-picture__body__subtitle
        %br
        人生を変えるフリマアプリ
      %p.top-picture__body__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .top-picture__body__btn
        .top-picture__body__btn__btn-a
          = link_to "#", class: "top-picture__body__btn__btn-a" do
            =image_tag "app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "180x100"
        .top-picture__body__btn__btn-b
          .top-picture__body__btn__btn-b
            = link_to "#", class: "top-picture__body__btn__btn-b" do
              =image_tag "google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "180x100"

  .mean
    %h.mean__subtitle
    %ul.mean__lists

      %li.mean__lists__list
        .mean__lists__list__pic
          %span.mean__lists__list__pic__number 1
          =image_tag "pict-reason-01.jpg", width: "100%"
        %h.mean__lists__list__text
          %span.list__text__span 3分
          ですぐに出品
        %p.mean__lists__list__description
          スマホで入力するだけで簡単に出品で
          きる！

      %li.mean__lists__list
        .mean__lists__list__pic
          %span.mean__lists__list__pic__number 2
          =image_tag "pict-reason-02.jpg", width: "100%"
        %h.mean__lists__list__text
          %span.list__text__span シンプル
          で使いやすい
        %p.mean__lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.mean__lists__list
        .mean__lists__list__pic
          %span.mean__lists__list__pic__number 3
          =image_tag "pict-reason-03.jpg", width: "100%"
        %h.mean__lists__list__text
          手数料
          %span.list__text__span 業界最安
        %p.mean__lists__list__description
          最大3%でお得に出品&購入！

  .middle-picture
    .middle-picture__body
      %h.middle-picture__body__subtitle
        %br
        会員数日本一位
      %p.middle-picture__body__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .middle-picture__body__btn
        .middle-picture__body__btn__btn-a
          = link_to "#", class: "middle-picture__body__btn__btn-a" do
            =image_tag "app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "180x100"
        .middle-picture__body__btn__btn-b
          .top-picture__body__btn__btn-b
            = link_to "#", class: "middle-picture__body__btn__btn-b" do
              =image_tag "google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "180x100"

  .feature
    %h.feature__subtitle
    .feature__lists

      .feature__lists__list
        .feature__lists__list__pic
          =image_tag "left-icon-01-7f6abf70ea7deaed9ab5d8b6d5cb796250e3e292b9ecdc559ebe6492c31fdab8.svg", width: "70%"
        %h.mean__lists__list__text
          簡単に売り買いできる
        %p.mean__lists__list__description
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！

      .feature__lists__list
        .feature__lists__list__pic
          =image_tag "right-icon-04-c4052f85cd6e1f62ea8cac8c55277d7fa4bda971d924f8a2afe72eea6558fa85.svg", width: "70%"
        %h.mean__lists__list__text
          売上金は即日振込みに対応
        %p.mean__lists__list__description
          午前9時までに振込を依頼いた
          だければ、翌日に指定の口座に
          入金いたします!

      .feature__lists__list
        .feature__lists__list__pic
          =image_tag "center-icon-03-9c0d78266a316fec7b738dcf5c68dd987afb9655b13fd2cd5d30bcf09e827694.svg", width: "70%"
        %h.mean__lists__list__text
          様々な支払いに対応
        %p.mean__lists__list__description
          お支払いは、クレジットカード
          だけでなく、ポイントや売上金
          など多彩な方法があります。


  .pick-ups
    .pick-ups__box
      %h.pick-ups__box__title
        ピックアップカテゴリー
      .pick-ups__box__link-title
        = link_to "#", class: "pick-ups__box__link-title" do
          新規投稿商品
          .pick-ups__box__goods
            - @goods.each do |good|
              .pick-ups__box__goods__list
                = link_to good_path(good.id), class: "pick-ups__box__goods__list" do
                  %li.pick-ups__box__goods__list__pic
                    =image_tag good.good_images[0].image.url, size: "220x150"
                  .pick-ups__box__goods__list__body
                    %li.pick-ups__box__goods__list__body__name= good.name
                    %li.pick-ups__box__goods__list__body__price
                      = converting_to_jpy(good.price)
                      %span.pick-ups__box__goods__list__body__price 円
                      %p.tax-included (税込)

    .pick-ups__box
      %h.pick-ups__box__title
        ピックアップカテゴリー
      .pick-ups__box__link-title
        = link_to "#", class: "pick-ups__box__link-title" do
          レディース新着アイテム
          .pick-ups__box__goods
            - @goods_women_new.each do |good|
              - if good.buyer_id == nil
                .pick-ups__box__goods__list
                  = link_to good_path(good.id), class: "pick-ups__box__goods__list" do
                    %li.pick-ups__box__goods__list__pic
                      =image_tag good.good_images[0].image.url, size: "220x150"
                    .pick-ups__box__goods__list__body
                      %li.pick-ups__box__goods__list__body__name= good.name
                      %li.pick-ups__box__goods__list__body__price
                        = converting_to_jpy(good.price)
                        %span.pick-ups__box__goods__list__body__price 円
                        %p.tax-included (税込)
              - else

    .pick-ups__box
      %h.pick-ups__box__title
        ピックアップカテゴリー
      .pick-ups__box__link-title
        = link_to "#", class: "pick-ups__box__link-title" do
          メンズ新着アイテム
          .pick-ups__box__goods
            - @goods_mens_new.each do |good| 
              - if good.buyer_id == nil 
                .pick-ups__box__goods__list
                  = link_to good_path(good.id), class: "pick-ups__box__goods__list" do
                    %li.pick-ups__box__goods__list__pic
                      =image_tag good.good_images[0].image.url, size: "220x150"
                    .pick-ups__box__goods__list__body
                      %li.pick-ups__box__goods__list__body__name= good.name
                      %li.pick-ups__box__goods__list__body__price
                        = converting_to_jpy(good.price) 
                        %span.pick-ups__box__goods__list__body__price 円
                        %p.tax-included (税込)
              - else


  .brand
    .brand__container
      %h.brand__container__title
        ピックアップブランド
      .brand__container__link-title
        = link_to "#", class: "brand__container__link-title" do
          アーカイバ
      .brand__container__category
        - @goods.zip(@good_images).each do |good, good_images|
          - if good.buyer_id == nil
            .brand__container__category__list
              = link_to good_path(good.id), class: "brand__container__category__list" do
                %li.pick-ups__box__goods__list__pic
                  =image_tag good.good_images[0].image.url, size: "220x150"
                .pick-ups__box__goods__list__body
                  %li.pick-ups__box__goods__list__body__name= good.name
                  %li.pick-ups__box__goods__list__body__price
                    = converting_to_jpy(good.price)
                    %span.pick-ups__box__goods__list__body__price 円
                    %p.tax-included (税込)
          - else

  .bottom-picture
    .bottom-picture__body
      %h.bottom-picture__body__subtitle
        %br
        だれでもかんたん、人生を変えるフリマアプリ
      %p.bottom-picture__body__text
        今すぐ無料ダウンロード！
      .bottom-picture__body__btn
        = link_to "#", class: "bottom-picture__body__btn__btn-a" do
          =image_tag "app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", size: "180x100"
        .bottom-picture__body__btn__btn-b
          .bottom-picture__body__btn__btn-b
            = link_to "#", class: "bottom-picture__body__btn__btn-b" do
              =image_tag "google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", size: "180x100"
  
    .bottom-logo
      = link_to new_good_path,data: {"turbolinks" => false}, class: "bottom-logo" do
        %h.bottom-logo__text 出品する
        .bottom-logo__img
          =image_tag "camera-icon_camera-968c5ebaa05319bf1e2ad7508f852dd712504a4d26a1930d8bd87ec03ebcc37a.svg", width: "60%"
  
  = render "indfooter.html.haml"

app/views/goods/destroy.html.haml
.goRootPage
  %h1.goRootPage__icon
    = link_to root_path do
      = image_tag "logo.png",size: "134x36",alt:"FURIMA"
.main-delete
  .delete
    .delete__top
      商品の削除が完了しました！
    .delete__btn
      = link_to root_path do
        = submit_tag "TOPページに戻る" ,class: "btn"
    .delete__btn
      = link_to user_path(current_user.id), method: :get do
        = submit_tag "マイページに戻る" ,class: "btn"
.goRootPage
  %h1.goRootPage__icon
.footer
  %ul.contents
    %li.content
      %h2.content__title
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            %span  会社概要
        %li
          = link_to "#" do
            %span  プライバシーポリシー
        %li
          = link_to "#" do
            %span  FURIMA利用規約
        %li
          = link_to "#" do
            %span  ポイントに関する特約
    %li.content
      %h2.content__title
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            %span  カテゴリー一覧
        %li
          = link_to "#" do
            %span  ブランド一覧
    %li.content
      %h2.content__title
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            %span  FURIMAガイド
        %li
          = link_to "#" do
            %span  FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            %span  お知らせ
  .footer__logo
    %span.image
      = image_tag "logo-white.png", size:"134x36"
      %p  ©︎フリマ

app/views/goods/index.html.haml
= render "header.html.haml"
= render "indmain.html.haml"

app/views/goods/new.html.erb
<%= form_for @good do |f| %>
  商品名<%= f.text_field :name %><br>

  <%= f.submit %>
<% end %>

app/views/goods/show.html.haml
= render "header.html.haml"

.item-details
  .item-detail
    %ul.item-detail__breadcrumb
      %li.item-detail__breadcrumb__list
        = link_to "#" do
          %span #{@category_parent.name} >
      %li.item-detail__breadcrumb__list
        = link_to "#" do
          %span #{@category_children.name} >
      %li.item-detail__breadcrumb__list
        = link_to "#" do
          %span #{@category_grand_children.name}
    .item-detail__content
      %h2.item-detail__content__name
        = @good_detail.name
      .item-detail__content__img
        - @good_detail.good_images.each_with_index do |img,i|
          - if i == 0
            .item-detail__content__img__top
              = image_tag("#{img.image}",size:'450x450')
        .item-detail__content__img__bottom
          - @good_detail.good_images.each_with_index do |img,i|
            - if i != 0
              .item-detail__content__img__bottom__b
                = image_tag("#{img.image}",size:'100x100')
                
      .item-detail__content__price
        = converting_to_jpy(@good_detail.price)
        %span 円
      .item-detail__content__price__postsge
      (税込)送料込み

      - if @good_detail.buyer_id.present?
        .item-detail__content__sold-out
          SOLD OUT
      -else
        - if user_signed_in? && current_user.id == @good_detail.seller_id
          .item-detail__content__edit
            = link_to edit_good_path(@good_detail),data: {"turbolinks" => false}, method: :get do
              %span 商品を編集する
          .item-detail__content__destroy
            = link_to good_path(@good_detail), method: :delete, data: { confirm: '削除しますか？' } do
              %span 商品を削除する
        - else
          .item-detail__content__buy
            = link_to orders_path(@good_detail.id) do
              %span 購入画面に進む
              
      .item-detail__content__introduction
        .item-detail__content__introduction__title
          商品説明
        .item-detail__content__introduction__text
          = @good_detail.expanation
      .table
        %table
          %tr
            %th
              出品者
            %td
              = @good_user.nickname
          %tr
            %th
              カテゴリー
            %td
              = @category_parent.name
              %br
              >
              = @category_children.name
              %br
              >
              = @category_grand_children.name
          %tr
            %th
              ブランド
            %td
              なし
          %tr
            %th
              商品のサイズ
            %td
              = @good_size.name
          %tr
            %th
              商品の状態
            %td
              = @good_detail.state
          %tr
            %th
              配送料の負担
            %td
              = @good_detail.postage
          %tr
            %th
              発送元の地域
            %td
              = @good_detail.region
          %tr
            %th
              発送日の目安
            %td
              = @good_detail.shipping_date
      .item-detail__content__reactions
        %ul
          %li.item-detail__content__reactions__fav
            %p
              お気に入り
        %ul
          %li.item-detail__content__reactions__report
            = link_to "#" do
              %span 不適切な商品の通報
  .coments
    .coment
      %input(type="text" class="coment__zone")/
      .coment__note
        %p
          相手のことを考え丁寧なコメントを心がけましょう。
        %p
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %input(type="submit" class="coment__btn" value="コメントする")

app/views/goods/update.html.haml
.goRootPage
  %h1.goRootPage__icon
    = link_to root_path do
      = image_tag "logo.png",size: "134x36",alt:"FURIMA"
.main-delete
  .delete
    .delete__top
      商品の編集が完了しました！
    .delete__btn
      = link_to root_path do
        = submit_tag "TOPページに戻る" ,class: "btn"
    .delete__btn
      = link_to user_path(current_user.id), method: :get do
        = submit_tag "マイページに戻る" ,class: "btn"
.goRootPage
  %h1.goRootPage__icon
.footer
  %ul.contents
    %li.content
      %h2.content__title
        FURIMAについて
      %ul
        %li
          = link_to "#" do
            %span  会社概要
        %li
          = link_to "#" do
            %span  プライバシーポリシー
        %li
          = link_to "#" do
            %span  FURIMA利用規約
        %li
          = link_to "#" do
            %span  ポイントに関する特約
    %li.content
      %h2.content__title
        FURIMAを見る
      %ul
        %li
          = link_to "#" do
            %span  カテゴリー一覧
        %li
          = link_to "#" do
            %span  ブランド一覧
    %li.content
      %h2.content__title
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "#" do
            %span  FURIMAガイド
        %li
          = link_to "#" do
            %span  FURIMAロゴ利用ガイドライン
        %li
          = link_to "#" do
            %span  お知らせ
  .footer__logo
    %span.image
      = image_tag "logo-white.png", size:"134x36"
      %p  ©︎フリマ