config/routes.rb
Rails.application.routes.draw do
  get 'card/new'
  get 'card/show'
  devise_for :users
  root to: 'goods#index'
  resources :users, only:[:show, :destroy]

 

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
  
  
  resources :goods, only:[:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :good_images, only: [:index, :new, :create]
  end

  
  resources :orders, only: [:index] do
    collection do
      get 'index', to: 'orders#index'
      post 'pay', to: 'orders#pay'
      get 'done', to: 'orders#done'
    end
  end

  resources :users, only:[:goods_sale] do
    member do
      get 'goods_sale'
    end
  end

  resources :users, only:[:goods_buy] do
    member do
      get 'goods_buy'
    end
  end

  resources :users, only:[:goods_list] do
    member do
      get 'goods_list'
    end
  end

  namespace :api do
    resources controller: :goods, only: :child, defaults: { format: 'json' } do
      collection do
        get 'child'
      end
    end
    resources controller: :goods, only: :grand_child, defaults: { format: 'json' } do
      collection do
        get 'grand_child'
      end
    end
  end
  

end

app/models/card.rb
class Card < ApplicationRecord
  has_one :user

  with_options presence: true do
    validates :user_id
    validates :customer_id
    validates :card_id
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :create_hash

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end


  def show
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private
  def create_hash
    @contents = ["マイページ","お知らせ","やることリスト","いいね！一覧","出品する","下書き一覧","出品した商品-出品中","出品した商品-取引中","出品した商品-売却済み","購入した商品-取引中","購入した商品-過去の取引","ニュース一覧","評価一覧","ガイド","お問い合わせ"]
    @options = ["プロフィール","発送元・お届先住所変更","支払い方法","メール/パスワード","本人情報","電話番号の確認","ログアウト"]
    
    @bland = ["//pcweb-assets.mercdn.net/assets/img/card/visa.svg?1152353370","//pcweb-assets.mercdn.net/assets/img/card/master-card.svg?1152353370","//pcweb-assets.mercdn.net/assets/img/card/saison-card.svg?1152353370","//pcweb-assets.mercdn.net/assets/img/card/jcb.svg?1152353370","//pcweb-assets.mercdn.net/assets/img/card/american_express.svg?1152353370","//pcweb-assets.mercdn.net/assets/img/card/dinersclub.svg?1152353370","//pcweb-assets.mercdn.net/assets/img/card/discover.svg?1152353370"]
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/new.html.haml
= render "goods/header"

.main
  = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
    .card-content
      = render "users/mypage-side"
      .card-content__main
        %h2.card-content__main__top クレジットカード情報入力
        .group
          .group__text
            .group__text__main
              カード番号
            .group__text__require
              必須
          = text_field_tag "number", "", class: "card_registration", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %ul.card_lists
            -@bland.each do |bland|
              %li.card_lists__icon
                =image_tag bland, class:"bland_logo"
          .group
            .group__text
              .group__text__main
                有効期限
              .group__text__require
                必須
            .group__form
              %select#exp_month{name: "exp_month", type: "text", class: "select_tag"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月
              %select#exp_year{name: "exp_year", type: "text", class: "select_tag"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
          .group
            .group__text
              .group__text__main
                セキュリティコード
              .group__text__require
                必須
            .group__form
              = text_field_tag "cvc", "", class: "card_registration", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              .group__form--require
                =link_to "#", class:"require" do
                  カード裏面の番号とは？
          .registration
            .registration__btn
              #card_token
              = submit_tag "追加する", id: "token_submit"

=render "goods/indfooter"

app/views/card/show.html.haml
= render "goods/header"

.main

  .card-content
    = render "users/mypage-side"
    .card-content__main
      %h2.card-content__main__top 登録クレジットカード情報
      .group
        .group__text
          .group__text__main
            カード番号
          .numberField
            = "**** **** **** " + @default_card_information.last4
        %ul.card_lists
          -@bland.each do |bland|
            %li.card_lists__icon
              =image_tag bland, class:"bland_logo"
        .group
          .group__text
            .group__text__main
              有効期限
          .group__form
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
            %span 月
        .registration
          .registration__btn
            = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button.delete_btn 削除する


=render "goods/indfooter"